manually update version to 0.3.8
because:

```
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /usr/bin/git push --follow-tags --set-upstream origin main
Stderr:       | remote: error: GH006: Protected branch update failed for refs/heads/main.        
              | remote: error: Changes must be made through a pull request. 4 of 4 required status checks are expected.        
              | To https://github.com/ansible-community/antsichaut
              |  ! [remote rejected] main -> main (protected branch hook declined)
              | error: failed to push some refs to 'https://github.com/ansible-community/antsichaut'
```